# portCreateRepo.yaml

name: Port action - create repository
on:
  workflow_dispatch:
    inputs:
      name:
        type: string
jobs:
  create-repository:
    runs-on: ubuntu-latest
    name: Create repository
    steps:
      - name: create repo
        uses: octobay/create-repository-action@v1
        with:
          name: ${{ fromJson(inputs.port_payload).name }}
          access-token: ${{ secrets.ORG_ADMIN_TOKEN }} # the secret we created in the previous step
          private-repo: true
          initialize-repo: true
